name: to_do_app
description: "A new app for task management."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  mvc_pattern: ^8.12.0
  collection: ^1.19.1
  shared_preferences: ^2.0.15
  shimmer: ^3.0.0
  provider: ^6.0.3
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  google_sign_in: ^6.2.2
  cloud_firestore: ^5.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  package_rename: ^1.8.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - images/splash_app/
    - images/icon_app/

  fonts:
  - family: Inter
    fonts:
      - asset: fonts/inter/INTER-REGULAR.ttf
      - asset: fonts/inter/INTER-THIN.ttf
        weight: 100
      - asset: fonts/inter/INTER-EXTRALIGHT.ttf
        weight: 200
      - asset: fonts/inter/INTER-LIGHT.ttf
        weight: 300
      - asset: fonts/inter/INTER-MEDIUM.ttf
        weight: 500
      - asset: fonts/inter/INTER-SEMIBOLD.ttf
        weight: 600
      - asset: fonts/inter/INTER-BOLD.ttf
        weight: 700
      - asset: fonts/inter/INTER-EXTRABOLD.ttf
        weight: 800
      - asset: fonts/inter/INTER-BLACK.ttf
        weight: 900

package_rename_config:
  android:
    app_name: To-Do App
    package_name: com.celina.todoapp

flutter_icons:
# Add icon in this folder and complete the path. Then run: flutter pub get 
# Finally run: dart run flutter_launcher_icons
  # Global
  image_path: "images/icon_app/icon_app.png"
  # Android
  android: "launcher_icon"
  adaptive_icon_background: "#333333"
  # adaptive_icon_foreground: "images/icon_app/icon_app.png"
